#!/usr/bin/env bash
# sandbox_install.sh — isolated dependency install for security review.
#
# Creates a fresh venv under .sandbox-venv/ (NOT the project's main venv),
# installs ONLY from binary wheels (--only-binary :all:), and refuses to
# fall back to sdist. The user is expected to `unset AWS_PROFILE` etc.
# BEFORE running this — we don't do it for you because we don't know
# which creds you have configured.
#
# Use this when you want to install a new dep version + audit it in a
# disposable environment before committing it to the real venv.
#
# Docs: docs/security/HARDENING.md §5

set -euo pipefail

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
REPO_ROOT="$( cd -- "${SCRIPT_DIR}/.." &> /dev/null && pwd )"
cd "${REPO_ROOT}"

SANDBOX_DIR="${REPO_ROOT}/.sandbox-venv"

# Resolve a Python (prefer the same one the main project uses).
PY=""
for cand in python3.11 python3.12 python3 python; do
  if command -v "$cand" >/dev/null 2>&1; then
    PY="$cand"
    break
  fi
done
if [ -z "$PY" ]; then
  echo "FATAL: no Python found in PATH"
  exit 2
fi

echo "Sandbox install using $PY ($(${PY} --version 2>&1))"
echo

# Warn if the user has cloud creds loaded — we can't unset them for
# them, but we can prod.
WARNED=0
for var in AWS_ACCESS_KEY_ID AWS_PROFILE GOOGLE_APPLICATION_CREDENTIALS \
           AZURE_CLIENT_ID GITHUB_TOKEN GH_TOKEN; do
  if [ -n "${!var:-}" ]; then
    if [ "$WARNED" -eq 0 ]; then
      echo "⚠️  WARNING: cloud creds are set in this shell:"
      WARNED=1
    fi
    echo "    \$$var"
  fi
done
if [ "$WARNED" -eq 1 ]; then
  echo "    Run \`unset <VAR>\` for each before continuing, or accept that"
  echo "    a malicious install will see them."
  echo
fi

# Wipe + recreate the sandbox.
if [ -d "$SANDBOX_DIR" ]; then
  echo "Removing existing sandbox at $SANDBOX_DIR..."
  rm -rf "$SANDBOX_DIR"
fi
echo "Creating fresh sandbox venv at $SANDBOX_DIR..."
"$PY" -m venv "$SANDBOX_DIR"

# Resolve the sandbox python.
SBPY="$SANDBOX_DIR/bin/python"
if [ ! -x "$SBPY" ]; then
  # Windows-style layout fallback (rare on Bash but possible under Git Bash)
  SBPY="$SANDBOX_DIR/Scripts/python.exe"
fi

"$SBPY" -m pip install --quiet --upgrade pip pip-audit

# Install — wheels only, fail rather than fall back to sdist.
# Hash-verify if requirements-hashed.txt exists (the canonical
# pinned set generated by pip-tools), else fall back to the
# unhashed requirements.txt.
#
# Platform gate (Codex P1 on 2ced5b6): the committed hashed file
# is generated on Windows and pins Windows-only wheels like
# `tensorflow-intel==2.16.2`. On macOS/Linux, ``pip install
# --require-hashes`` aborts before sandbox setup completes and
# the unhashed fallback never runs. Detect compatibility by
# scanning the hashed file for the canonical Windows-only
# marker and falling through to the unhashed path on
# non-Windows hosts. (The fallback loses tamper detection but
# still installs wheel-only, which preserves the primary
# ``--only-binary :all:`` defence.)
HASHED_OK=0
if [ -f "requirements-hashed.txt" ]; then
  HASHED_OK=1
  if grep -qE '^tensorflow-intel==' requirements-hashed.txt; then
    case "$(uname -s)" in
      MINGW*|MSYS*|CYGWIN*|Windows_NT) ;;     # Windows / Git Bash — keep hashed path
      *) HASHED_OK=0 ;;                       # macOS / Linux — fall back
    esac
  fi
fi
if [ "$HASHED_OK" -eq 1 ]; then
  echo "Installing requirements-hashed.txt --require-hashes --only-binary :all:..."
  "$SBPY" -m pip install --require-hashes --only-binary :all: -r requirements-hashed.txt
else
  if [ -f "requirements-hashed.txt" ]; then
    echo "NOTE: requirements-hashed.txt is Windows-pinned; falling back to requirements.txt for this OS."
  fi
  echo "Installing requirements.txt --only-binary :all: (tamper detection OFF on this fallback path)..."
  "$SBPY" -m pip install --only-binary :all: -r requirements.txt
fi

echo
echo "=== Sandbox audit (pip-audit on the installed env) ==="
"$SBPY" -m pip_audit --strict --disable-pip --progress-spinner off

echo
echo "Sandbox is at: $SANDBOX_DIR"
# Show the correct activate path for the current platform — Git Bash
# on Windows creates `Scripts/activate`, not `bin/activate`. The
# script already auto-detects the python binary path above; mirror
# that for the activation hint. (Gemini medium on 9a20e14.)
if [ -d "$SANDBOX_DIR/Scripts" ]; then
  echo "Activate with:  source $SANDBOX_DIR/Scripts/activate"
else
  echo "Activate with:  source $SANDBOX_DIR/bin/activate"
fi
echo "Tear down:      rm -rf $SANDBOX_DIR"
